# version: "3.8"

# services:
#   backend:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     environment:
#       - PYTHONDONTWRITEBYTECODE=1
#       - PYTHONUNBUFFERED=1
#     depends_on:
#       - frontend  # Ensures frontend starts first

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#     environment:
#       - NODE_ENV=development


# docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./lre_project_v3.db
    volumes:
      - ./backend/lre_project_v3.db:/app/lre_project_v3.db
